### PR TITLE
Add Specifications

### PR DESCRIPTION
**Pull request by decibel**
Allow users to create an include/exclude list.

See also https://github.com/datarefuge/workflow/pull/45

### CODE REVIEW

**Comment by dcwalk** [comment]
@titaniumbones can you review?

**Comment by danielballan** [comment]
This looks good to me.

**Review by titaniumbones — COMMENTED** [review]
I agree w/ @danielballan that it looks good, and we should merge. Might be worth adding a couple of lines to the readme, too.  Thanks @decibel!

**Comment by titaniumbones** [comment]
never got merged, doing so now, thx @decibel (5 months later!)

**Pull request merged**
