### PR TITLE
[WIP] Cookbook

### PR DESCRIPTION
**Pull request by jeffreyliu**
DataRescue Boston is working on reworking the harvesting-tools repo to be more comprehensive and useful to harvesters. We intend this repo to function as a "cookbook" of sorts that thoroughly documents different common patterns for web scraping, and example code snippets/templates for people to use.

These changes restructures the repository to provide the skeleton for this rework. All of the existing code is preserved under the archive/ directory. We will be working to integrate those tools into the cookbook.

The other directories represent collections of recipes that address certain similar patterns:
- crawling/
    - def: following links; getting site topology
        - scrapy
- Robo-browsers/
    - def: emulates human interactions, dynamic front-end info
        - selenium-python
        - mechanize-ruby
- parsers/
    - def: searching through and parsing the DOM
        - beautiful soup
        - lxml
- downloading/
    - def: streaming data to local disk
        - wget
        - ftp
- site-specific/
    - def: examples of how to process specific websites
        - envi scraper
These are the initial collections, and we may add more in the future as needed to handle specific kinds of data sets that we encounter.

### CODE REVIEW

**Comment by dcwalk** [comment]
Hey @jeffreyliu this looks like a substantial restructure-- I'm wondering what the status is on it.. or if you are looking to have this reviewed or merged in? Maybe we could mark this "WIP" if it is a _work in progress_

There are a few conversations that have been going on across the `#dev` chat, stand ups, etc... around a shift in how the archivers.space app, as well as whole workflow and how people interact with our tools. I think it would be great to fold your work and rethinking around a cookbook in with those convos. I'm expecting @b5 to push a proposal mid-week on that.

Also, I'm concerned about the potential breadth of this change and how it will fit in with what we have (e.g. we'd need to review/update language across the workflow, event process and event planning documentation).

**Comment by jeffreyliu** [comment]
Hi,

Yes, it's a work on progress, and we'd decided to put in the first pull
request just to set the repo structure, so other people can start
contributing. I'm fine with keeping it as a separate branch until it's
ready to go live.

I don't see that it would impact the workflow in terms of event structure
much at all. It's meant to be a consolidation and reorganization of the
existing code base, with the addition of tools, tutorials, and examples to
make it easier for people to get started/identify appropriate tools for the
job.

Happy to adjust the scope to be consistent with the new archivers app's
goals when they're available.

Best,
Jeff

**Comment by dcwalk** [comment]
Thanks for clarification, I've renamed to add WIP for now.

In terms of impact I didn't mean the actual on the ground workflow--I mean all the supporting documentation (and _language_) we have will need to be updated, I'd rather minimize the amount of times we do this as we just went through a round of updates.

It wasn't my intent to say this should be developed separately. In my experience merging in after long periods of separate development can be messy. I actually think it might be easier to work on this part:
> thoroughly documents different common patterns for web scraping, and example code snippets/templates for people to use.

...in smaller chunks and merge in regularly rather than fully developing on a parallel branch.
I'm interpreting that to include: 
- standarization of documentation for each tool, (which we are sorely lacking!!).
- adding  new tools (e.g., `beautiful soup`, `lxml`as well as our jquery extractor) 

Before working on a major reorg of the tools locations and language around how we refer to these.

**Comment by dcwalk** [comment]
Also-- why "robo-browser" verses "[headless browser](https://dhamaniasad.github.io/HeadlessBrowsers/)"? I'm not too aware of how this stuff is discussed within scraping community, maybe we should link out to some excellent scraping resources across languages

Are there complementary pattern languages we should be referencing?

**Comment by jeffreyliu** [comment]
Yeah, we'd also prefer smaller regular updates and merges too.

If I understand correctly, you're proposing that we keep the flat directory
structure for the time being, but work on developing additional tools and
documentation before we approach the restructuring? I'm fine with this
approach, as long as we are allowed to embed somewhere (perhaps the README)
a "soft" set of categorizations/structure that organizes the different
patterns. We'd like to categorize by pattern rather than by tool/language,
because that makes the harvester's job easier, and hopefully helps avoid
the Maslow's hammer pitfall.

Re: robo vs headless browsers, personally I'm not a huge fan of the
"headless" nomenclature, since some of the tools actually do generate a
real browser window and render the DOM (and as such require a [possibly
virtual] display). To me, headless suggests there's no GUI being rendered,
but tools like selenium can render and interact with, for example, canvas
elements. But the headless designation seems to be more common, and I can
see how robo-browser may be confusing since there's an implementation of a
headless browser called robobrowser, so I'm fine with renaming that
category.

We're not referencing a specific pattern language currently, but to be
honest, I haven't looked too deeply into whether there are any relevant
existing collections of patterns. We'll probably uncover more existing
resources that we can refer to as we expand the toolset.

Thanks,
-Jeff

**Comment by jonganc** [comment]
Hi. I am working with @jeffreyliu in Boston on this categorization. I am sympathetic with your (i.e. from @dcwalk) resistance to what looks like a huge recategorization. The problem with the current organization is that it's just a laundry list of tools. In practice, people will have a problem with a certain type of task, like "how do I scrape using a robobrowser/headless browser" or maybe "how do I extract data from an arcgis file"?

However, this requires a very different organizational structure than the current one. The original tools and documentation are useful and would be reincorporated into the new sections (putting them in archives would just be temporary). But without some kind of structural scaffolding (i.e. the directory structure), I think it might be hard to keep this reorganization straight and effectively let different people work on the different sections independently.

There are some compromise scenarios, like keeping the original directories and adding the new folders, where we could link to the originals, etc. On the other hand, this might lead to the repository getting very cluttered.

It is clearly the responsibility of the proposers to (try to) convince you that our proposal makes sense; we should bat the idea around and see what others have to say. However, to summarize, my 2-cents is that trying to accomplish equivalent changes gradually would be ineffective.

**Comment by dcwalk** [comment]
@jonganc --- I'm all for improving the organization of these tools. My main concern, as I've said, is minimizing the pain of changes to this repo across all of the other event support material we have. Especially as we are expecting major changes within a couple weeks across all our event materials. @jeffreyliu appears to be onboard with incremental changes before finalizing the restructure and so that seems like a way forward that could work. 

Once all the tools and consistent documentation is added, wouldn't moving to the new structure be relatively short work, rather than gradually moving in tools from an 'achive'?

In terms of making sure that there isn't duplication of work, I think we could make use of existing communication channels: creating issues in this github repo and then assigning them to parties working on them, as well as communicating in #dev, in order to ensure there isn't any duplication. I don't see this being a major challenge, especially if you are all working as a tight group in Boston.

**Comment by jonganc** [comment]
@dcwalk -- I'm, in principle, sympathetic to the issue of coordinating this with how new events are organized (though I should note that, at least at the event I went to, this repo was not widely unused, which is why we proposed the reorganization). However, our understanding is that, in all proposed reorganizations, there will still be a need for a clear cookbook of techniques for pages that require manual scraping. Though I suppose that some aspects of the content could depend on the way the scraping will proceeed, we believe (maybe overly optimistically...?) that the divisions we suggest would be pretty stable under reorganization plans.

I also realize I may be a little unclear about about what are you are suggesting we do. Is it: 1) you want to think/discuss more about the details of the new organization we propose; 2) you think the overall idea is reasonable but want us to suggest the changes in a piecemeal fashion; e.g. when we have a robobrowser/headless browsing folder ready, we make a pull request just for that folder and related content; 3) you think we should wait for the project restructuring.

I actually am not very experienced with git. so I may be missing things that you see.

**Comment by dcwalk** [comment]
@jonganc one of the proposals for the future of events would be a move away from manual scraping/downloading as it currently functions, so I think there is definitely the potential at future events for the role of attendees to look radically different, and the nature of the tools to shift too. As an event materials coordinator and organizer I have a strong interest in ensuring these changes reflect across our other materials and how new events are organized.

I'm proposing this (quoting @jeffreyliu) :
> that we keep the flat directory structure for the time being, but work on developing additional tools and documentation before we approach the restructuring? I'm fine with this approach, as long as we are allowed to embed somewhere (perhaps the README) a "soft" set of categorizations/structure that organizes the different patterns. 

A potential set of steps for this change:
1. Submit a PR with the categorization in README (I'd prefer headless v. robo-browser based on convo above)
1. Add new tools and submit them separately as PRs
1. Update/improve/make consistent documentation across tools
1. Finally, propose a folder restructure as a PR

Feel free to open PRs with [WIP] to mark that you are working on an area, or open issues and we can assign them to contributors leading those changes.

**Comment by dcwalk** [comment]
I'm going to leave this PR open with [WIP], feel free to close or have this branch continue to track your progress across other PRs

**Comment by titaniumbones** [comment]
Hi folks, sorry for my long delay in reviewing this. I really like @dcwalk's proposal -- I know it slows things down for the Boston group and that this may feel frustrating. But we are making a *big effort* to work in a more systematic way, and I really think the best way to work here is in coordination with other parts of the project. This will mitigate splintering and help reduce duplication of effort across the project (IMO).

**Review by titaniumbones — CHANGES_REQUESTED** [review]
As @dcwalk suggests: 
```
    Submit a PR with the categorization in README (I'd prefer headless v. robo-browser based on convo above)
    Add new tools and submit them separately as PRs
    Update/improve/make consistent documentation across tools
    Finally, propose a folder restructure as a PR
```

**Comment by dcwalk** [comment]
I'm wondering if we are good to close this as the work on Cookbook/patterns is happening in https://github.com/datatogether/archivertools

@titaniumbones or @jeffreyliu?

**Comment by jeffreyliu** [comment]
No objections to closing this!

**Comment by titaniumbones** [comment]
no objections from me either!

**Pull request closed without merging**
